spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:rom7774256}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
  liquibase:
    user: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:rom7774256}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test}
    contexts: dev
  devtools:
    restart:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health , prometheus

logging:
  level:
    root: WARN
#  file:
#    name: filelog.log
#    path: /             Сохраняет логи в файле