spring:
  application:
    name: spring-guru
  datasource:
    hikari:
      pool-name: RestDB-Pool
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/my_guru
    username: postgres
    password: rom7774256
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    enabled: false



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          spingauth:
            client-id: messaging-client
            client-secret: secret
            scope:
              - message.read
              - message.write
            authorization-grant-type: client_credentials
            provider: springauth
        provider:
          springauth:
            authorization-uri: http://localhost:9000/auth2/authorize
            token-uri: http://localhost:9000/auth2/token
#    user:
#      name: user
#      password: password

#  data:
#    rest:
#      base-path: /api/v1/rests

rest:
  template:
    rootUrl: http://localhost:8080
#    username: user
#    password: password

logging:
  level:
    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
      example:
        springguru: debug
#      springframework.security: trace