spring:
  application:
    name: gateway-spring
  cloud:
    gateway:
      mvc:
        routes:
          - id: gate-spring
            uri: http://localhost:8080
            predicates:
              - Path=/beer
#        httpserver:
#          wiretap: true
#        httpclient:
#          wiretap: true
#
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org:
#      springframework:
#        cloud:
#          gateway: trace
#        http:
#          server:
#            reactive: trace
server:
  port: 8081
