spring:
  application:
    name: java-u-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: rom7774256
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate

logging:
  level:
    root: WARN
#  file:
#    name: filelog.log
#    path: /             Сохраняет логи в файле