spring:
  application:
    name: security-best

  datasource:
    username: postgres
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180
#        opaquetoken:
#          introspection-uri: http://localhost:8180
#          client-id: intospect
#          client-secret: ckek34IikmmO93

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}